### ISSUE TITLE
anything here? 

### ISSUE THREAD

**Issue by brlinf-06398** [Mythril382/ThisThing#1]
Platform: *Windows 10 64 bit

Build: The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.
Version: release build 146 (Foo's client version: a854598 unstable)

Issue: Explain your issue in detail.
Can't initialize the game. the game closes when it's loading. I updated the mod and still crashes.

Steps to reproduce: How you happened across the issue, and what exactly you did to make the bug happen.
Starting up the game. it loads till I get an error message.

Link(s) to mod(s) used: The mod repositories or zip files that are related to the issue, if applicable.
https://github.com/Mythril382/ThisThing

Save file: The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. You can save the game to a slot even if you're playing on someone's server.

Crash report: The contents of relevant crash report files. Please be sure to get this resolved if you are reporting a crash.
[crash-report-10_21_2023_14_52_20.txt](https://github.com/Mythril382/ThisThing/files/13060132/crash-report-10_21_2023_14_52_20.txt)

Version: release build 146
(Foo's Client Version: a854598, Oct. 20, 2023 Unstable)
Source: mindustry-antigrief/mindustry-client-v7-builds
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 8176mb
Cores: 12
Mods: betamindy:1.1, camod:135, this-thing:1.6.0, toggle-editor-mode:2.2, yr2-logic-debugger:1.7.1

arc.util.ArcRuntimeException: java.lang.NullPointerException: Cannot invoke "arc.files.Fi.nameWithoutExtension()" because "file" is null
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:672)
	at arc.assets.AssetManager.update(AssetManager.java:442)
	at arc.assets.AssetManager.update(AssetManager.java:465)
	at mindustry.ClientLauncher.update(ClientLauncher.java:228)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:205)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:193)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:57)
Caused by: java.lang.NullPointerException: Cannot invoke "arc.files.Fi.nameWithoutExtension()" because "file" is null
	at thing.logic.TTLogic.setupConstants(TTLogic.java:31)
	at thing.logic.TTLogic.load(TTLogic.java:22)
	at thing.ThisThing.loadContent(ThisThing.java:35)
	at mindustry.mod.Mods.loadContent(Mods.java:724)
	at mindustry.core.ContentLoader.createModContent(ContentLoader.java:83)
	at mindustry.ClientLauncher.lambda$setup$5(ClientLauncher.java:170)
	at arc.assets.AssetManager$1.loadSync(AssetManager.java:334)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:108)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:73)
	at arc.assets.AssetManager.updateTask(AssetManager.java:591)
	at arc.assets.AssetManager.update(AssetManager.java:440)
	... 6 more

Place an X (no spaces) between the brackets to confirm that you have read the line below.

[X ] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
[X ] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Mythril382** [comment]
among us

**Comment by Mythril382** [comment]
Issue fixed in latest update.

**Comment by eris-webserv** [comment]
issue is reoccuring on latest fooclient
